[type-out]
strings = [
    "I'm in love with porn...",
    "furry porn has ruined me forever 🥵🥵🥵",
    "Thank you for existing, Furry Porn.",
    "HNNNGGGGHHH",
    "Furry porn has taken over my life and i don't care at all lmao",
    "It feels so good to let go and be consumed by PORN.",
    "I am so fucking horny right now...",
    "Furry porn has ruined me forever NGGGGGHHHH",
]